spring:
  datasource:
    url: jdbc:mysql://localhost:3306/allocation_db?createDatabaseIfNotExist=true
    username: spring
    password: springpwd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
  application:
    name: allocation_db
server:
  port: 8080