spring:
  datasource:
    url: jdbc:mysql://localhost:3306/allocation_db?createDatabaseIfNotExist=true
    username: service
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: allocator

server:
  port: 8180