spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db?createDatabaseIfNotExist=true
    username: kusal
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
  application:
    name: company_db
server:
  port: 8080