spring:
  datasource:
    url: jdbc:mysql://localhost:8060/employee_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
  application:
    name: employee_db
server:
  port: 8080